# Generated by Django 2.1 on 2018-08-21 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0065_merge_20180821_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name - പേര്')),
                ('address', models.TextField(verbose_name='Address - വിലാസം')),
                ('contacts', models.CharField(blank=True, max_length=250, null=True, verbose_name='Contacts - മൊബൈൽ')),
                ('type_of_materials_collecting', models.TextField(blank=True, null=True, verbose_name='Type of materials collecting - ശേഖരിക്കുന്ന വസ്തുക്കൾ ')),
                ('district', models.CharField(blank=True, choices=[('alp', 'Alappuzha - ആലപ്പുഴ'), ('ekm', 'Ernakulam - എറണാകുളം'), ('idk', 'Idukki - ഇടുക്കി'), ('knr', 'Kannur - കണ്ണൂർ'), ('ksr', 'Kasaragod - കാസർഗോഡ്'), ('kol', 'Kollam - കൊല്ലം'), ('ktm', 'Kottayam - കോട്ടയം'), ('koz', 'Kozhikode - കോഴിക്കോട്'), ('mpm', 'Malappuram - മലപ്പുറം'), ('pkd', 'Palakkad - പാലക്കാട്'), ('ptm', 'Pathanamthitta - പത്തനംതിട്ട'), ('tvm', 'Thiruvananthapuram - തിരുവനന്തപുരം'), ('tcr', 'Thrissur - തൃശ്ശൂർ'), ('wnd', 'Wayanad - വയനാട്')], max_length=15, null=True, verbose_name='Ceter District - ജില്ല')),
                ('lsg_type', models.SmallIntegerField(blank=True, choices=[(0, 'Corporation'), (1, 'Municipality'), (2, 'Grama Panchayath')], null=True, verbose_name='LSG Type - തദ്ദേശ സ്വയംഭരണ സ്ഥാപനം')),
                ('lsg_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='LSG Name - സ്വയംഭരണ സ്ഥാപനത്തിന്റെ പേര്')),
                ('ward_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ward - വാർഡ്')),
                ('is_inside_kerala', models.BooleanField(verbose_name='Center inside kerala? - കേന്ദ്രം കേരളത്തിലാണോ')),
                ('city', models.CharField(max_length=150, verbose_name='City - നഗരം')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
